name: Cypress Cloud

on: 
  workflow_dispatch:
    inputs:
      spec:  
        description: Run by cypress command line
        default: cypress/e2e/*

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.2.1

      - name: Cypress.io
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: e32c16a6-2183-4f63-96ca-d06fe29310f1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    
